#!/bin/sh

# Get commit count from main branch
COMMIT_COUNT=$(git rev-list --count main)
# Get datetime in the correct format
DATETIME=$(date '+%m%d.%H%M')
# Combine for final version
VERSION="${COMMIT_COUNT}.${DATETIME}"

# Update version.txt
echo "$VERSION" > src/version.txt

# Add the updated version.txt to the commit
git add src/version.txt

# Exit successfully
exit 0 