/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TemplateCreateImport } from './routes/template-create'
import { Route as SettingsImport } from './routes/settings'
import { Route as IndexImport } from './routes/index'
import { Route as TemplateEditIdImport } from './routes/template-edit.$id'

// Create/Update Routes

const TemplateCreateRoute = TemplateCreateImport.update({
  id: '/template-create',
  path: '/template-create',
  getParentRoute: () => rootRoute,
} as any)

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TemplateEditIdRoute = TemplateEditIdImport.update({
  id: '/template-edit/$id',
  path: '/template-edit/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/template-create': {
      id: '/template-create'
      path: '/template-create'
      fullPath: '/template-create'
      preLoaderRoute: typeof TemplateCreateImport
      parentRoute: typeof rootRoute
    }
    '/template-edit/$id': {
      id: '/template-edit/$id'
      path: '/template-edit/$id'
      fullPath: '/template-edit/$id'
      preLoaderRoute: typeof TemplateEditIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/template-create': typeof TemplateCreateRoute
  '/template-edit/$id': typeof TemplateEditIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/template-create': typeof TemplateCreateRoute
  '/template-edit/$id': typeof TemplateEditIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/template-create': typeof TemplateCreateRoute
  '/template-edit/$id': typeof TemplateEditIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/template-create' | '/template-edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/template-create' | '/template-edit/$id'
  id: '__root__' | '/' | '/settings' | '/template-create' | '/template-edit/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  TemplateCreateRoute: typeof TemplateCreateRoute
  TemplateEditIdRoute: typeof TemplateEditIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  TemplateCreateRoute: TemplateCreateRoute,
  TemplateEditIdRoute: TemplateEditIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/settings",
        "/template-create",
        "/template-edit/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/template-create": {
      "filePath": "template-create.tsx"
    },
    "/template-edit/$id": {
      "filePath": "template-edit.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
