name: Calculate Version

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calculate version
        id: version
        run: |
          COMMIT_COUNT=$(git rev-list --count main)
          DATETIME=$(date '+%m%d.%H%M')
          VERSION="${COMMIT_COUNT}.${DATETIME}"
          echo "$VERSION" > src/version.txt
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Commit version update
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add src/version.txt
          git commit -m "chore: Update version to $VERSION" || echo "No changes to commit"
          git push
